// TREND
export const FETCH_TREND_SUCCESS = "FETCH_TREND_SUCCESS";
export const FETCH_TREND_ERROR = "FETCH_TREND_ERROR";

// GOVERNING EQUATIONS
export const FETCH_GOVERNING_EQUATIONS_SUCCESS =
  "FETCH_GOVERNING_EQUATIONS_SUCCESS";
export const FETCH_GOVERNING_EQUATIONS_ERROR =
  "FETCH_GOVERNING_EQUATIONS_ERROR";

// GOVERNING EQUATIONS_GREEKS
export const FETCH_GOVERNING_EQUATIONS_GREEKS_SUCCESS =
  "FETCH_GOVERNING_EQUATIONS_GREEKS_SUCCESS";
export const FETCH_GOVERNING_EQUATIONS_GREEKS_ERROR =
  "FETCH_GOVERNING_EQUATIONS_GREEKS_ERROR";

// volatility-surface
export const FETCH_METRICS_CALLS_SURFACE_SUCCESS =
  "FETCH_METRICS_CALLS_SURFACE_SUCCESS";
export const FETCH_METRICS_CALLS_SURFACE_ERROR =
  "FETCH_METRICS_CALLS_SURFACE_ERROR";

// PERFORMANCE_BENCHMARK
export const FETCH_PERFORMANCE_BENCHMARK_SUCCESS =
  "FETCH_PERFORMANCE_BENCHMARK_SUCCESS";
export const FETCH_PERFORMANCE_BENCHMARK_ERROR =
  "FETCH_PERFORMANCE_BENCHMARK_ERROR";

// AUTTOCORRELATION
export const FETCH_AUTTOCORRELATION_SUCCESS = "FETCH_AUTTOCORRELATION_SUCCESS";
export const FETCH_AUTTOCORRELATION_ERROR = "FETCH_AUTTOCORRELATION_ERROR";

// PARTIAL AUTO CORRELATION
export const FETCH_PARTIAL_AUTO_CORRELATION_SUCCESS =
  "FETCH_PARTIAL_AUTO_CORRELATION_SUCCESS";
export const FETCH_PARTIAL_AUTO_CORRELATION_ERROR =
  "FETCH_PARTIAL_AUTO_CORRELATION_ERROR";

// SUBSTITUTION RATE
export const FETCH_SUBSTITUTION_RATE_SUCCESS =
  "FETCH_SUBSTITUTION_RATE_SUCCESS";
export const FETCH_SUBSTITUTION_RATE_ERROR = "FETCH_SUBSTITUTION_RATE_ERROR";
export const FETCH_SUBSTITUTION_RATE_LOAD = "FETCH_SUBSTITUTION_RATE_LOAD";

// SUBSTITUTION RATE CORR
export const FETCH_SUBSTITUTION_RATE_CORR_SUCCESS =
  "FETCH_SUBSTITUTION_RATE_CORR_SUCCESS";
export const FETCH_SUBSTITUTION_RATE_CORR_ERROR =
  "FETCH_SUBSTITUTION_RATE_CORR_ERROR";
export const FETCH_SUBSTITUTION_RATE_CORR_LOAD =
  "FETCH_SUBSTITUTION_RATE_CORR_LOAD";

// Seasonal decompose
export const FETCH_SEASONAL_DECOMPOSE_SUCCESS =
  "FETCH_SEASONAL_DECOMPOSE_SUCCESS";
export const FETCH_SEASONAL_DECOMPOSE_ERROR = "FETCH_SEASONAL_DECOMPOSE_ERROR";

// implied volatility
export const FETCH_IMPLIED_VOLATILITY_SUCCESS =
  "FETCH_IMPLIED_VOLATILITY_SUCCESS";
export const FETCH_IMPLIED_VOLATILITY_ERROR = "FETCH_IMPLIED_VOLATILITY_ERROR";

// implied volatility
export const FETCH_ROLLING_CORRELATIONS_SUCCESS =
  "FETCH_ROLLING_CORRELATIONS_SUCCESS";
export const FETCH_ROLLING_CORRELATIONS_ERROR =
  "FETCH_ROLLING_CORRELATIONS_ERROR";

// ROLLING FLOW
export const FETCH_ROLLING_FLOW_SUCCESS = "FETCH_ROLLING_FLOW_SUCCESS";
export const FETCH_ROLLING_FLOW_ERROR = "FETCH_ROLLING_FLOW_ERROR";

// ROLLING Mads
export const FETCH_ROLLING_MADS_SUCCESS = "FETCH_ROLLING_MADS_SUCCESS";
export const FETCH_ROLLING_MADS_ERROR = "FETCH_ROLLING_MADS_ERROR";

// Mads Dist
export const FETCH_MADS_DIST_SUCCESS = "FETCH_MADS_DIST_SUCCESS";
export const FETCH_MADS_DIST_ERROR = "FETCH_MADS_DIST_ERROR";

// Hurst Exponent
export const FETCH_HURST_EXPONENT_SUCCESS = "FETCH_HURST_EXPONENT_SUCCESS";
export const FETCH_HURST_EXPONENT_ERROR = "FETCH_HURST_EXPONENT_ERROR";

// HODLER DISTRIBUTION
export const FETCH_HODLER_DISTRIBUTION_SUCCESS =
  "FETCH_HODLER_DISTRIBUTION_SUCCESS";
export const FETCH_HODLER_DISTRIBUTION_ERROR =
  "FETCH_ROLLING_CORRELATIONS_ERROR";

// EXCHANGE FLOW
export const FETCH_EXCHANGE_FLOW_SUCCESS = "FETCH_EXCHANGE_FLOW_SUCCESS";
export const FETCH_EXCHANGE_FLOW_ERROR = "FETCH_EXCHANGE_FLOW_ERROR";

// ROLLING ENTHROPY
export const FETCH_ROLLING_ENTHROPY_SUCCESS = "FETCH_ROLLING_ENTHROPY_SUCCESS";
export const FETCH_ROLLING_ENTHROPY_ERROR = "FETCH_ROLLING_ENTHROPY_ERROR";

// cost of product
export const FETCH_COST_OF_PRODUCT_SUCCESS = "FETCH_COST_OF_PRODUCT_SUCCESS";
export const FETCH_COST_OF_PRODUCT_ERROR = "FETCH_COST_OF_PRODUCT_ERROR";

// SCATTERED PLOTS
export const FETCH_SCATTERED_PLOTS_SUCCESS = "FETCH_SCATTERED_PLOTS_SUCCESS";
export const FETCH_SCATTERED_PLOTS_ERROR = "FETCH_SCATTERED_PLOTS_ERROR";

// efficuency Index
export const FETCH_EFFICIENCY_INDEX_SUCCESS = "FETCH_EFFICIENCY_INDEX_SUCCESS";
export const FETCH_EFFICIENCY_INDEX_ERROR = "FETCH_EFFICIENCY_INDEX_ERROR";

// 3d1
export const FETCH_3D1_SUCCESS = "FETCH_3D1_SUCCESS";
export const FETCH_3D1_ERROR = "FETCH_3D1_ERROR";

// 3d2
export const FETCH_3D2_SUCCESS = "FETCH_3D2_SUCCESS";
export const FETCH_3D2_ERROR = "FETCH_3D2_ERROR";

// 3d3
export const FETCH_3D3_SUCCESS = "FETCH_3D3_SUCCESS";
export const FETCH_3D3_ERROR = "FETCH_3D3_ERROR";

// RESIDUAL PLOT //
export const FETCH_RESIDUAL_PLOT_SUCCESS = "FETCH_RESIDUAL_PLOT_SUCCESS";
export const FETCH_RESIDUAL_PLOT_ERROR = "FETCH_RESIDUAL_PLOT_ERROR";

// BTC ROLLING
export const FETCH_BTC_ROLLING_SUCCESS = "FETCH_BTC_ROLLING_SUCCESS";
export const FETCH_BTC_ROLLING_ERROR = "FETCH_BTC_ROLLING_ERROR";

// RESIDUAL HISTOGRAM //
export const FETCH_RESIDUAL_HIST_SUCCESS = "FETCH_RESIDUAL_HIST_SUCCESS";
export const FETCH_RESIDUAL_HIST_ERROR = "FETCH_RESIDUAL_HIST_ERROR";

// BTC RETURN DISTRIBUTION
export const FETCH_BTC_RETURN_DIS_SUCCESS = "FETCH_BTC_RETURN_DIS_SUCCESS";
export const FETCH_BTC_RETURN_DIS_ERROR = "FETCH_BTC_RETURN_DIS_ERROR";

// QQ PLOT //
export const FETCH_QQ_PLOT_SUCCESS = "FETCH_QQ_PLOT_SUCCESS";
export const FETCH_QQ_PLOT_ERROR = "FETCH_QQ_PLOT_ERROR";

// PROBABILITY PLOT //
export const FETCH_PROB_PLOT_SUCCESS = "FETCH_PROB_PLOT_SUCCESS";
export const FETCH_PROB_PLOT_ERROR = "FETCH_PROB_PLOT_ERROR";

// METRIC //
export const FETCH_METRIC_SUCCESS = "FETCH_METRIC_SUCCESS";
export const FETCH_METRIC_ERROR = "FETCH_METRIC_ERROR";

//CHANGE_ZT_LEARNER
export const CHANGE_ZT_LEARNER = "CHANGE_ZT_LEARNER";

// MODAL //
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL_DATA = "OPEN_MODAL_DATA";
export const CLOSE_MODAL_DATA = "CLOSE_MODAL_DATA";
export const OPEN_MODAL_PUBLICATION = "OPEN_MODAL_PUBLICATION";
export const CLOSE_MODAL_PUBLICATION = "CLOSE_MODAL_PUBLICATION";

//  COOKIES
export const CLOSE_COOKIES = "CLOSE_COOKIES";

// DASHBOARD NAVIGATION //
export const LOAD_DASHBOARD_PAGE_SUCCESS = "LOAD_DASHBOARD_PAGE_SUCCESS";
export const LOAD_DASHBOARD_PAGE_SUCCESS_RESEARCH =
  "LOAD_DASHBOARD_PAGE_SUCCESS_RESEARCH";
export const LOAD_DASHBOARD_PAGE_SUCCESS_FORECAST =
  "LOAD_DASHBOARD_PAGE_SUCCESS_FORECAST";

// DATA STEPS NAVIGATION //
export const NEXT_DATA_STEP = "NEXT_DATA_STEP";
export const PREV_DATA_STEP = "PREV_DATA_STEP";
export const ENABLE_DOWNLOADS = "ENABLE_DOWNLOADS";

// RESEARCH //
export const TOGGLE_TAG = "TOGGLE_TAG";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";

// NUMBER OF HOURS //
export const HOURS_NUMBER = "HOURS_NUMBER";

// GET_DISCORD
export const GET_DISCORD = "GET_DISCORD";
export const GET_DISCORD_ERROR = "GET_DISCORD_ERROR";

// RESOURCES
export const SET_RESOURCES_OPEN = "SET_RESOURCES_OPEN";
export const DEFAULT_RESOURCES = "DEFAULT_RESOURCES";

// PDF
export const SET_PDF = "SET_PDF";

//user login
export const USER_LOGIN = "USER_LOGIN";
